name: codeworld-template

custom-setup:
  dependencies:
    - base
    - Cabal
    - cabal-doctest >=1.0.2 && <1.1

dependencies:
  - base >= 4.7 && < 5
  - codeworld-api == 0.8.1

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

library:
  source-dirs: src

executables:
  codeworld-template:
    main: Main.hs
    source-dirs: app
    dependencies:
      - codeworld-template

tests:
  spec:
    main:                Spec.hs
    source-dirs:         tests
    dependencies:
    - codeworld-template
    - hspec
    build-tools:
    - hspec-discover:hspec-discover
  doctests:
    source-dirs: tests
    main: doctests.hs
    other-modules: []
    dependencies:
      - base
      - doctest
