name: go-time

custom-setup:
  dependencies:
    - base
    - Cabal
    - cabal-doctest >=1.0.2 && <1.1

dependencies:
  - base >= 4.7 && < 5
  - codeworld-api == 0.8.1
  - text
  - hashmap

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

library:
  source-dirs: src

executables:
  go-time:
    main: Main.hs
    source-dirs: app
    dependencies:
      - go-time

tests:
  spec:
    main:                Spec.hs
    source-dirs:         tests
    dependencies:
    - go-time
    - hspec
    build-tools:
    - hspec-discover:hspec-discover
  doctests:
    source-dirs: tests
    main: doctests.hs
    other-modules: []
    dependencies:
      - base
      - doctest
